### ISSUE TITLE
pip returns error when installing

### ISSUE THREAD

**Issue by k-ogawa-1988** [ados1991/py3dns#2]
Hello,
I faced this error when installing py3dns by pip3.6

# Conclusion

I see the source code [DNS/Base.py](https://github.com/ados1991/py3dns/blob/master/DNS/Base.py#L9), I think you need to add `# -*- coding: utf-8 -*-` at top of the file because you use non-ascii character at line 9 `©`.
ref: https://stackoverflow.com/questions/18078851/syntaxerror-of-non-ascii-character

Please check and fix if it is true.

# Log
```
[ec2-user@blah ~]$ sudo -H pip install py3dns
Collecting py3dns
  Using cached https://files.pythonhosted.org/packages/87/0d/35d3d710ec6ca04d5e5f8b344c6604fc9590629918346801cc5e7425cc4a/py3dns-3.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rVU2G_/py3dns/setup.py", line 7, in <module>
        import DNS
      File "/tmp/pip-build-rVU2G_/py3dns/DNS/__init__.py", line 27, in <module>
        from .Base import DnsRequest
      File "/tmp/pip-build-rVU2G_/py3dns/DNS/Base.py", line 9
    SyntaxError: Non-ASCII character '\xc2' in file /tmp/pip-build-rVU2G_/py3dns/DNS/Base.py on line 10, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rVU2G_/py3dns/
```

# Environment

Server: Amazon Linux 2018.03
Python: 3.6
Py3DNS: 3.1.0

Regards,

**Comment by k-ogawa-1988** [comment]
Sorry, I found a launchpad, so I wrote bug report there.
https://bugs.launchpad.net/py3dns/+bug/1774134
